GET http://localhost:3000/subscribers

### 
GET http://localhost:3000/subscribers/6187744257aae534a9c1826f

### 

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "alex",
    "subscribedToChannel": "GT"
}

###

DELETE http://localhost:3000/subscribers/6187744257aae534a9c1826f

###

PATCH http://localhost:3000/subscribers/61877858721e8a28b5ac28a1
Content-Type: application/json

{
    "name": "alexwdwefwefewttttttstt",
    "subscribedToChannel": "GT"
}